const SET_REV_LOC = "SET_REV_LOC";
const SET_OPTION = "SET_OPTION";
const SET_WEATHER = "SET_WEATHER";
const SET_WEATHER_DESC = "SET_WEATHER_DESC";

export { SET_REV_LOC, SET_OPTION, SET_WEATHER, SET_WEATHER_DESC };
